name: v2free-daily-attendance
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    # needs: test

    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: echo ${{secrets.DOCKERPASSWORD}} | docker login -u ${{secrets.DOCKERUSER}} --password-stdin
      - name: Build And Push Image
        run: |
          docker build -t ${{secrets.DOCKERUSER}}/v2free-daily-attendance .
          docker push ${{secrets.DOCKERUSER}}/v2free-daily-attendance
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVICEHOST }}
          username: ${{ secrets.SERVICEUSER }}
          key: ${{secrets.SERVICESECRET}}
          script: |
            # 停止旧版容器
            docker stop $(docker ps --filter ancestor=jehadsama/v2free-daily-attendance -q)
            # 删除旧版容器
            docker rm -f $(docker ps -a --filter ancestor=jehadsama/v2free-daily-attendance -q)
            # 删除旧版镜像
            docker rmi -f $(docker images jehadsama/v2free-daily-attendance -q)
            # 登录镜像服务器
            echo ${{secrets.DOCKERPASSWORD}} | docker login -u ${{ secrets.DOCKERUSER }} --password-stdin
            # 拉取最新latest版本镜像
            docker pull jehadsama/v2free-daily-attendance
            # 运行最新latest版本镜像
            docker run --name v2free_sch --network=my-net --restart=always -d -e CK=${{ secrets.CK }} jehadsama/v2free-daily-attendance
